---
initial_setup_gnome_group_x86_64: 
  - "Workstation"
initial_setup_gnome_group_aarch64: 
  - "GNOME"
  - "Workstation product core"
initial_setup_devel_group: "Development Tools"

extra_packages:
  - qemu-guest-agent
  - wget 
  - ca-certificates 
  - nano 
  - less 
  - iproute
  - net-tools 
  - procps-ng
  - sqlite
  - telnet 
  - bind9.16-utils

wireshark_packages:
  - wireshark
  - wireshark-common
  - wireshark-dev
