---
- name: Install reccaster
  include_tasks: "{{ epics_build_module_task }}"
  vars:
    epics_modules_to_build: "{{ m_reccaster_modules }}"
  when: not (m_reccaster_installed | default(false))

- name: Mark m_reccaster as installed
  set_fact:
    m_reccaster_installed: true
