---
# Install cashark plugins
#
- name: ensure directory exists
  become: true
  ansible.builtin.file:
    path: "{{ wireshark_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: install plugin files
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/mdavidsaver/cashark/refs/heads/master/{{ item }}
    dest: "{{ wireshark_config_dir }}"
    mode: '0644'
  loop:
    - ca.lua
    - pva.lua

- name: ensure wireshark init file exists
  become: true
  ansible.builtin.file:
    path: "{{ wireshark_config_dir }}/init.lua"
    state: present
    owner: root
    group: root
    mode: '0644'

- name: enable lua plugins - remove any existing definition
  become: true
  ansible.builtin.lineinfile:
    path: "{{ wireshark_config_dir }}/init.lua"
    search_string: disable_lua
    state: absent

- name: enable lua plugins - explicitly enable
  become: true
  ansible.builtin.lineinfile:
    path: "{{ wireshark_config_dir }}/init.lua"
    line: "{{ item }}" 
    state: present
    insertafter: EOF
  loop:
    - 'disable_lua = false'
    - 'dofile("ca.lua")'
    - 'dofile("pva.lua")'


-
