---
# Allow creation of wireshark group
- name: configure wireshark-common
  become: true
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: 'true'
    vtype: select

- name: install wireshark
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  ansible.builtin.apt:
    name: "{{ wireshark_packages }}"

- name: install wireshark
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  ansible.builtin.dnf:
    name: "{{ wireshark_packages }}"

# TODO: work out how to ensure wireshark group created in RedHat
- name: add epics-dev to wireshark group
  become: true
  ansible.builtin.user:
    name: "{{ dev_user }}"
    append: true
    groups: 
      - wireshark
