---
- name: check if the URL is valid
  ignore_errors: true
  ansible.builtin.uri:
    url: "{{ item.url }}"
  register: result

- name: Run IOC installation tasks
  when: "result.status == 200"
  become: true
  become_user: "{{ epics_run_user }}"
  vars:
    ansible_remote_tmp: "{{ epics_run_user_tmp }}"
  block:

  - name: Install {{ item.name }} IOC
    ansible.builtin.git:
      repo: "{{ item.url }}"
      dest: "{{ ioc_install_dir }}/{{ item.path }}"

