---
- name: check if the URL is valid
  ansible.builtin.uri:
    url: "{{ item.url }}"
  register: result

- name: Run IOC installation tasks
  when: "result is not failed"
  become: true
  become_user: "{{ epics_run_user }}"
  block:

  - name: Install {{ item.name }} IOC
    ansible.builtin.git:
      repo: "{{ item.url }}"
      dest: "{{ ioc_install_dir }}/{{ item.path }}"

