---
- name: check if the URL is valid
  ignore_errors: true
  ansible.builtin.uri:
    url: "{{ item.url }}"
  register: result

- name: Run IOC installation tasks
  become: true
  when: "result.status == 200"
  block:

  - name: Install {{ item.name }} IOC
    become_user: "{{ epics_run_user }}"
    vars:
      ansible_remote_tmp: "{{ epics_run_user_tmp }}"
    ansible.builtin.git:
      repo: "{{ item.url }}"
      dest: "{{ ioc_install_dir }}/{{ item.path }}"

  - name: Build {{ item.name }} IOC
    become_user: "{{ epics_run_user }}"
    vars:
      ansible_remote_tmp: "{{ epics_run_user_tmp }}"
    ansible.builtin.command:
      cmd: make
      chdir: "{{ ioc_install_dir }}/{{ item.path }}"

  - name: Create log directory 
    become_user: root
    ansible.builtin.file:
      path: /var/log/procServ
      owner: "{{ epics_run_user }}"
      group: "{{ epics_run_user }}"
      mode: '0755'
      state: directory

  - name: Create run directory
    become_user: root
    ansible.builtin.file:
      path: /run/ioc@ioc{{ item.ioc_name }}
      owner: "{{ epics_run_user }}"
      group: "{{ epics_run_user }}"
      mode: '0755'
      state: directory

  - name: Create systemd unit file for {{ item.name }} IOC
    become_user: root
    ansible.builtin.template:
      src: ioc@.service.j2
      dest: /etc/systemd/system/ioc@ioc{{ item.ioc_name }}.service

  - name: Enable and start IOC process
    become_user: root
    ansible.builtin.systemd_service:
      name: ioc@ioc{{ item.ioc_name}}.service
      daemon_reload: true
      state: restarted
      enabled: true

