---
# Create IOC top-level directory
- name: Create IOC top-level directory
  ansible.builtin.file:
    path: "{{ ioc_install_dir }}"
    state: directory
    owner: epics-dev
    group: epics-dev
    mode: 0755

# Install IOCs
- name: Install ramp IOC
  include_tasks: install_ramp_ioc.yml
  when: iocs is defined and iocs | bool
