---
# Create IOC top-level directory
- name: Create IOC top-level directory
  become: true
  ansible.builtin.file:
    path: "{{ ioc_install_dir }}"
    state: directory
    owner: epics-dev
    group: epics-dev
    mode: 0755

# Install IOCs
- name: Install  IOCs
  include_tasks: install_iocs.yml
  when: iocs is defined and iocs | bool
  loop: "{{ ioc_list }}"
