---
timezone: Europe/Berlin

homepage_docs:
  - file: bash_commands.html
    descriptor: Bash commands
    link: 60-bash
  - file: iocsh_commands.html
    descriptor: iocsh commands
    link: 61-iocsh
  - file: epics_commands.html
    descriptor: epics commands
    link: 62-epics
