---

# Create host elasticsearch directory
- name: Create elasticsearch directory
  become_method: containers.podman.podman_unshare
  become: true
  ansible.builtin.file:
    path: "{{ elasticsearch_directory }}"
    owner: epics-dev
    group: epics-dev
    mode: '0777'
    state: directory

# Install elasticsearch container
- name: Install elasticsearch container
  containers.podman.podman_container:
    name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ elasticsearch_version }}
    state: started
    env:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      network.host: "127.0.0.1"
      bootstrap.memory_lock: "true"
    volume: "{{ elasticsearch_directory }}:/usr/share/elasticsearch/data:Z"
    network: host
    auto_remove: true
    health_cmd: "curl http://localhost:9200/"
    healthcheck_start_period: "10m"


