--- 
- name: Create channelfinder container
  containers.podman.podman_container:
    name: channelfinder
    image: ghcr.io/channefinder/channefinder:{{ channelfinder_version }}
    state: quadlet
    env:
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      network.host: "127.0.0.1"
      bootstrap.memory_lock: "true"
    network: host
    auto_remove: true
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target

- name: Enable channelfinder container
  become: true
  ansible.builtin.systemd:
    name: channelfinder
    daemon-reload: true
    state: started
    enabled: true
