---
# Install Elasticsearch container
- name: Install elasticsearch
  ansible.builtin.include_tasks:
    file: install_elasticsearch.yml

# Install channelfinder container
#- name: Install channelfinder
#ansible.builtin.include_tasks:
#file: install_channelfinder.yml
